const nombre = localStorage.getItem('nombre');
console.log(nombre);
if(nombre == "Alex"){
    document.getElementById('title-aventura').innerHTML = "Ciudad de las Sombras <br>("+ nombre +")";
    document.getElementById('txt-story').innerHTML = "El auto se detuvo frente a la entrada de la ciudad abandonada, y Alex fue la primera en bajar. Miró a su alrededor, con una mezcla de fascinación y nervios. Los edificios ruinosos, los grafitis en las paredes y el silbido del viento entre las calles desiertas le daban al lugar una atmósfera casi de otro mundo.<br><br>'Bueno, esto es más espeluznante de lo que pensé,' dijo, tratando de romper la tensión. Giró sobre sus talones para observar mejor el entorno. '¿Quién quiere explorar primero?'<br><br>Pull sugirió quedarse juntos, pero Alex sabía que no duraría mucho esa sensatez. Kita ya estaba bromeando sobre fantasmas, y aunque Luxar intentó mantener la calma, era claro que también estaba intrigado. Illa, como siempre, fue el primero en moverse hacia la plaza central.<br><br>Alex caminó junto a ellos, sintiendo la energía del grupo. La ciudad tenía una calma inquietante, como si el tiempo se hubiera detenido. Encontraron tiendas vacías, autos oxidados y, en el centro, una iglesia imponente que dominaba el paisaje.<br><br>Fue Alex quien notó los primeros signos extraños. 'Chicos... miren eso.' Señaló un símbolo pintado con lo que parecía sangre seca: un círculo con una cruz y letras incomprensibles.<br><br>'Es graffiti, ¿no?' dijo Kita, aunque su tono mostraba dudas.<br><br>'No lo creo,' respondió Alex, observando de cerca. Algo en el aire se sentía diferente, como si ese lugar guardara secretos peligrosos.<br><br>Siguieron explorando y encontraron más signos, velas apagadas y, finalmente, un altar con objetos perturbadores. Alex sintió un escalofrío, pero trató de mantenerse tranquila.<br><br>'Esto no me gusta nada,' dijo Luxar, rompiendo el silencio.<br><br>De repente, pasos resonaron afuera. Alex se asomó por una ventana rota y vio figuras encapuchadas caminando hacia la iglesia.<br><br>'¿Qué demonios...?' susurró, sintiendo el corazón acelerado.<br><br>Pull insistió en irse, pero Kita propuso seguirlos. 'Esto podría ser la mejor historia de nuestras vidas,' dijo, y Alex no pudo evitar sonreír nerviosa. La idea era peligrosa, pero también emocionante.<br><br>Antes de que pudieran decidir, una campana resonó desde la iglesia. Las figuras se detuvieron y giraron lentamente sus cabezas hacia la casa donde estaban escondidos.<br><br>'Nos vieron,' susurró Alex, sintiendo un nudo en el estómago.<br><br>El grupo se dispersó en pánico. Alex corrió junto a Illa y Kita hacia la iglesia, mientras Pull y Luxar buscaban un camino al auto. Sabía que Bebu estaba atrapado en medio de las dos opciones. Alex solo esperaba que él tomara la decisión correcta.";

}else if(nombre == "Luxar"){
    document.getElementById('title-aventura').innerHTML = "Ciudad de las Sombras <br>("+ nombre +")";
}else if(nombre == "Illa"){
    document.getElementById('title-aventura').innerHTML = "Ciudad de las Sombras <br>("+ nombre +")";
}else if(nombre == "Kita"){
    document.getElementById('title-aventura').innerHTML = "Ciudad de las Sombras <br>("+ nombre +")";
}else if(nombre == "Pull"){
    document.getElementById('title-aventura').innerHTML = "Ciudad de las Sombras <br>("+ nombre +")";
}else if(nombre == "Bebu"){
    document.getElementById('title-aventura').innerHTML = "Ciudad de las Sombras <br>("+ nombre +")";
    document.getElementById('txt-story').innerHTML = "El grupo llegó a una ciudad abandonada al caer la tarde. La carretera había quedado atrás, y los edificios rotos y grafitis daban al lugar un aire inquietante.<br><br>Bebu, mezcla de curiosidad y nervios, lideró la idea tras oír rumores en internet. Este viaje era su oportunidad de salir de su zona de confort con sus amigos.<br><br>'Bueno, esto es más espeluznante de lo que pensé,' dijo Alex, mirando alrededor. '¿Quién explora primero?'<br><br>'Quedémonos juntos,' sugirió Pull. 'No sabemos qué hay aquí.'<br><br>'¿Qué podría salir mal?' respondió Kita, riendo. 'No hay fantasmas.'<br><br>Luxar asintió. 'Igual, no nos separemos.'<br><br>El grupo avanzó explorando calles desiertas. Encontraron tiendas vacías, autos oxidados y una iglesia imponente en el centro.<br><br>'Chicos, miren eso,' dijo Alex, señalando un símbolo pintado con sangre seca: un círculo con una cruz y letras extrañas.<br><br>'Es graffiti, ¿no?' dijo Kita, menos confiado.<br><br>'No parece,' murmuró Bebu. 'Esto es un símbolo.'<br><br>Hallaron más signos, velas y un altar con velas negras y estatuillas grotescas.<br><br>'Esto no me gusta,' dijo Luxar.<br><br>Pasos resonaron afuera. Figuras encapuchadas caminaban hacia la iglesia.<br><br>'Tenemos que irnos,' dijo Pull.<br><br>'Veamos qué hacen,' sugirió Kita.<br><br>'¡Estás loco!' respondió Illa.<br><br>Bebu dudó, dividido entre escapar con Pull y Luxar o quedarse con Kita, Alex e Illa, que querían respuestas. Su corazón latía con fuerza. Tenía que elegir.";
}
